### ISSUE TITLE
Fix character encoding for email address

### ISSUE THREAD

**Issue by emurnane** [emurnane/EmailDrivenAppsEngine#13]
On the landing page, special character `@` being displayed as `%40`. For example: "Email data for e.l.murnane%40gmail.com ready to be played."

Probably want something like: `URLDecoder.decode(url)` or `URLDecoder.decode(url, "UTF-8")`

**Comment by ik226** [comment]
I have made commits on this 
please check the pull request

**Comment by emurnane** [comment]
Looks good, see commits https://github.com/emurnane/EmailDrivenAppsEngine/commit/bc9fc545c10f153f2dea1695395ddef672f9f290 and https://github.com/emurnane/EmailDrivenAppsEngine/commit/a33dc680f2588adf6d89be2d2fe25739712a0a81
