### ISSUE TITLE
Display the time being played

### ISSUE THREAD

**Issue by emurnane** [emurnane/EmailDrivenAppsEngine#21]
- [x] Display the time being played in the game in the top center of the screen. 
- [x] Make it 12 hours time and show AM or PM: "Current wave: 6:00 PM" (rather than 18:00).

**Comment by ik226** [comment]
please check the pull request :)

**Comment by emurnane** [comment]
Looks good! See commits https://github.com/emurnane/EmailDrivenAppsEngine/pull/32
