### ISSUE TITLE
Combine pages to enter email and select role and add an instructions page

### ISSUE THREAD

**Issue by emurnane** [emurnane/EmailDrivenAppsEngine#3]
Landing page (http://moodrhythm.com:5001/spacegame/) currently prompts user to enter email and press "Play" button. Pressing "Play" then displays the message "We will need to read your email data before we can play", requests Role at Cornell, and has another button which redirects to authentication and then launches the game. Let's combine these two pages in the following ways and add an instruction page:
- [x] On the landing page, add one line that explains what user should do: "Please enter your email address and job role." 
- [x] On line below that have one line with a text field: [ Enter your email address ]
- [x] On the line below that, have a dropdown: [ Select your role ]
- [x] Change options in dropdown to these: Undergraduate Student, Masters Student, Doctoral Student, PostDoc, Staff, Faculty, Other
- [x] Make button say "Next". 
- [x] Pressing that button should bring the user to authentication, which then redirects back to a message saying "Loading your data...". Change this page to have the loading message and contain the below instructions.
- [x] After data finishes loading, page automatically redirects to a page that says, "Email data for xx@gmail.com ready to be played". Change "Email data for..." etc to instead say, "Data successfully loaded! Please read the instructions below, and press 'Start Game' when you are ready to play." Keep the button that says "Start Game" but add these instructions below it:

**How to Play:** 
You are the ship, and your goal is to defend yourself from the oncoming enemy ships that will appear as the day progresses (as the sun moves across the sky and the hours on the clock in the [top left corner of the screen] tick by). In order to avoid hitting enemies (which will inflict damage upon you), use the up and down arrow keys to move your ship and the left and right arrow keys to rotate your ship. Fire bullets using the XX key to inflict damage upon your enemies. If you find yourself without any bullets to fire at enemies, you will just have to dodge them!

The number of enemy ships corresponds to the number of emails you receive at that time of day, and the number of bullets you have to fire at those ships corresponds to the number of emails you send at that time of day. Enemy attributes represent characteristics of that email: 
- Enemy Color: Domain of sender's email address (Red = Cornell; Blue = Non-Cornell academic, i.e., @*.edu; Green = Gmail, Hotmail, or Yahoo; White: Other domains).
- Enemy Size: Length of that received email
- Enemy Speed: Number of recipients of that received email (enemy is fastest if you are the only recipient and gets slower the the higher the number of other recipients).

You start with 3 lives — you can see how many you have left in the upper right hand corner. You gain points for each enemy you destroy and each “hour” you stay alive, and you level up at the end of each “day”. Try to survive as long as possible! If the game ends — either because you win or lose — feel free to restart and replay it as many times as you like.

**Comment by ik226** [comment]
I am wondering where this instruction should be placed.
I have found that the '/spacegame/index.html' contains some instructions inside a section, #infoPage, however it is hidden by 'style = "display:none;"'. 
I guess the flow to be 1.index.html -->(entering email/ set data according to email) --[bug]--> 2. spacegame/index.html (where the modules are loaded by SGmain.js)
Should we update the spacegame/index.html page? 
Also, please let me know if the intended flow is different from what I have understood.

**Comment by emurnane** [comment]
The index file you'll want to modify is actually located at public/index.html (i.e., http://cornellhci.org/tailormade/EmailDrivenAppsEngine/public/index.html), rather than public/spacegame/index.html (i.e., http://cornellhci.org/tailormade/EmailDrivenAppsEngine/public/spacegame/index.html — if you visit that in your browser, you'll see there's no game available there but rather at the former link). 

I've also updated the issue to provide more details about the flow and be more specific about the changes necessary.

**Comment by emurnane** [comment]
Just updated the comment to provide more detail.

**Comment by emurnane** [comment]
Great! See commits https://github.com/emurnane/EmailDrivenAppsEngine/commit/9f74dae76192a0537e20295a819b793f8ca0326c and https://github.com/emurnane/EmailDrivenAppsEngine/commit/152382ee8418f7da8fce336087454c92179ef100
